### ISSUE TITLE
GitHub Icon is hiding in mobile view.

### ISSUE THREAD

**Issue by saswatsamal** [hackclub/leaderboard#1]
The floating icon of GitHub is hiding in the mobile view under the cards.
You can check the attached photo for further reference:
![image](https://user-images.githubusercontent.com/39031660/130330182-b9c7b027-ca77-4601-b5f5-759a7c0de450.png)

![image](https://user-images.githubusercontent.com/39031660/130330187-a348e147-775d-471f-b759-eed5e0af1124.png)

**Comment by bajpai244** [comment]
Hey, Thanks for letting us know about it, the issue has been fixed.
